import {notFound} from "next/navigation";

const orderUrl="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes";
const img={
 sides:"https://static.spotapps.co/spots/c9/8f265be6d64e4fa455a6e9421a0dd4/full",
 nigiri:"https://static.spotapps.co/spots/b9/4ffdf1e852484a90061289ba98cfc7/full",
 classic:"https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full",
 specialty:"https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full",
 ramen:"https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full",
 tiramisu:"https://static.spotapps.co/spots/56/031328c8ed48eabc685c378ce80859/full",
 guava:"https://static.spotapps.co/spots/81/548e0a2f0f4cbf86a8bbd67079d39c/full",
 strawberry:"https://static.spotapps.co/spots/49/cf50f1e2c047ca85d908170f4fa18d/full",
 passion:"https://static.spotapps.co/spots/58/f6b5fa4b88425abcf44260cde9851b/full",
 still:"https://static.spotapps.co/spots/e3/a4cf0cbd0545be875e5f25a082fa24/full",
 adriana:"https://static.spotapps.co/spots/5e/2c1afb6a71456cae33a86586a70aa7/full",
 burg:"https://static.spotapps.co/spots/1e/625e4f72784322b93a681619b32b35/full",
 volcano:"https://static.spotapps.co/spots/19/df68b6b6464223ab75475f858e73cf/full"
};
const items={
"sushi-gunkan":{name:"Sushi Gunkan",price:"12",image:img.sides,category:"SIGNATURE SIDE",desc:"Rice wrapped with nori. Choose three: lion’s mane, toona, lobstah or sckallops.",taste:"Savory and umami-forward, with the character changing depending on the three toppings you choose.",texture:"Tender rice and crisp nori underneath soft, composed toppings.",pairing:"House sake",story:"This is a tasting-format plate: several House flavors, one compact order, and a good way to compare how different plant-based ingredients behave in sushi form."},
"edamame":{name:"Edamame",price:"8",image:img.sides,category:"SIGNATURE SIDE",desc:"Steamed edamame, gochujang garlic sesame dusting and Thai chili sauce.",taste:"Garlicky, sesame-rich and lightly spicy.",texture:"Tender beans with a seasoned exterior and a little bite from the chili finish.",pairing:"Sapporo",story:"The House takes a familiar starter and pushes it toward more heat, aroma and seasoning so it earns its place beside the rolls."},
"seaweed-salad":{name:"Seaweed Salad",price:"7",image:img.sides,category:"SIGNATURE SIDE",desc:"Wakame finished with sesame seeds.",taste:"Clean, lightly sweet and oceanic.",texture:"Cool, delicate and slightly crisp.",pairing:"Pinot Grigio",story:"This is the bright reset on the table: cold, clean and simple enough to sit between richer, saucier dishes."},
"nigiri-sampler":{name:"Nigiri Sampler",price:"12",image:img.nigiri,category:"NIGIRI",desc:"Unagi, spicy toona, sckallop and smoked salmon.",taste:"A range from smoky to spicy to savory, all in one tasting sequence.",texture:"Soft toppings over compact seasoned rice.",pairing:"Bushido Sake",story:"The sampler gives you four different expressions of House-style nigiri without committing to a single flavor profile."},
"smoked-salmon-nigiri":{name:"Smoked Salmon Nigiri",price:"12",image:img.nigiri,category:"NIGIRI",desc:"Vegan smoked salmon, spicy mayo, eel sauce, torched and finished with scallions.",taste:"Smoky, creamy and sweet-savory.",texture:"Silky topping over tender rice with a lightly torched finish.",pairing:"Pinot Grigio",story:"A single bite designed around smoke, sauce and texture rather than imitation alone."},
"nigiri":{name:"Nigiri",price:"6",image:img.nigiri,category:"NIGIRI",desc:"Choose spicy toona, unagi or sckallop truffle.",taste:"Choose spicy, sweet-savory or earthy-truffle depending on the topping.",texture:"Soft topping over seasoned rice.",pairing:"Sake",story:"This is the build-your-own tasting move: order one style or line up several to compare them side by side."},
"tom-kha-ramen":{name:"Tom Kha Ramen",price:"15",image:img.ramen,category:"RAMEN",desc:"Chili lemongrass coconut broth with corn, scallions and vegan vork belly.",taste:"Creamy coconut, bright lemongrass and chili warmth.",texture:"Silky broth with noodles, corn and tender vegan vork belly.",pairing:"Malbec",story:"A comfort bowl that brings Thai-inspired aromatics into the House menu and gives the sushi-focused menu a warmer, deeper counterpoint."},
"california-roll":{name:"California Roll",price:"16.50",image:img.classic,category:"CLASSIC ROLL",desc:"Cucumber, avocado and garlicky jackfruit salad.",taste:"Fresh, creamy and savory with a garlicky finish.",texture:"Crisp cucumber, soft avocado and tender jackfruit.",pairing:"Pinot Grigio",story:"A familiar maki structure rebuilt with jackfruit so the roll still reads as comforting and recognizable without relying on seafood."},
"spicy-krab":{name:"Spicy Krab",price:"16.50",image:img.classic,category:"CLASSIC ROLL",desc:"King oyster mushroom krab, marinated carrots, cucumber and avocado.",taste:"Savory, mildly spicy and fresh.",texture:"Tender mushroom krab against crisp cucumber and creamy avocado.",pairing:"Riesling",story:"King oyster mushroom gives this classic-style roll a meaty bite while the vegetables keep it bright and balanced."},
"philadelphia-roll":{name:"Philadelphia Roll",price:"17.50",image:img.classic,category:"CLASSIC ROLL",desc:"Carrot lox, avocado, cucumber and cream cheese with vegan eel sauce.",taste:"Smoky-sweet, creamy and cool.",texture:"Soft carrot lox and cream cheese with crisp cucumber.",pairing:"Pinot Grigio",story:"The House version keeps the creamy, smoky logic people expect from a Philadelphia-style roll while rebuilding every component around plants."},
"spicy-toona":{name:"Spicy Toona",price:"16",image:img.classic,category:"CLASSIC ROLL",desc:"Marinated tomato toona, avocado and cucumber with spicy mayo.",taste:"Bright tomato, creamy avocado and a spicy mayo finish.",texture:"Silky marinated tomato against crisp cucumber.",pairing:"Riesling",story:"Tomato becomes the center of the roll here, carrying seasoning and moisture in a way that makes the plant-based construction feel intentional rather than substituted."},
"sweet-potato-summer-roll":{name:"Sweet Potato Summer Roll",price:"16",image:img.classic,category:"CLASSIC ROLL",desc:"Sweet potato, mango, cucumber, marinated carrots and avocado.",taste:"Sweet, fresh and fruit-forward.",texture:"Soft sweet potato and avocado with crisp cucumber and carrots.",pairing:"Pinot Grigio",story:"This is one of the brighter classic rolls on the menu, built around produce, sweetness and clean contrast."},
"avocado-cucumber-roll":{name:"Avocado Cucumber Roll",price:"8.50",image:img.classic,category:"CLASSIC ROLL",desc:"Maki-style avocado and cucumber.",taste:"Clean, mild and creamy.",texture:"Crisp cucumber with soft avocado.",pairing:"Sake",story:"The simplest roll on the menu is also the clearest expression of balance: rice, nori, cucumber and avocado with nowhere to hide."},
"volcano-roll":{name:"Volcano Roll",price:"23",image:img.volcano,category:"SPECIALTY ROLL",desc:"Avocado, carrot and cucumber beneath spicy lion’s mane seafood dynamite, vegan caviar and house sauces.",taste:"Hot, creamy and savory with a pronounced spicy finish.",texture:"Cool vegetables underneath a rich, saucy lion’s mane topping.",pairing:"Malbec",story:"The louder side of the House: heat, sauce and contrast piled onto a cool vegetable base."},
"still-i-rise":{name:"Still I Rise",price:"24",image:img.still,category:"SPECIALTY ROLL",desc:"Spicy king oyster krab and cucumber topped with scorched avocado, vegan caviar and butter-poached vegan lobstah.",taste:"Creamy, savory and gently spicy with a rich finish.",texture:"Tender mushroom krab, cool cucumber, silky avocado and buttery lobstah.",pairing:"Pinot Grigio",story:"A layered House signature built to move from freshness into richness without losing balance."},
"the-burg":{name:"The Burg",price:"23",image:img.burg,category:"SPECIALTY ROLL",desc:"Eggplant, cucumber, tempura crumbs, torched avocado, lion’s mane, king oyster and vegan lobstah.",taste:"Smoky, rich and savory with a torched finish.",texture:"Crunch from tempura against tender mushrooms and soft avocado.",pairing:"Old Red Vine Zinfandel",story:"The Burg leans into char, depth and the mushroom-forward side of the House menu."},
"adriana-vegano-sparkle-ii":{name:"Adriana “Vegano” Sparkle II",price:"24",image:img.adriana,category:"SPECIALTY ROLL",desc:"Vegan sckallop, cucumber and avocado topped with house toona tartare and 24-karat gold sparkle.",taste:"Bright, creamy and luxurious with a clean ocean-inspired profile.",texture:"Soft sckallop, crisp cucumber, creamy avocado and silky toona tartare.",pairing:"Riesling",story:"One of the House showpieces: celebratory, polished and intentionally dramatic."},
"king-krab-roll":{name:"King Krab Roll",price:"21",image:img.specialty,category:"SPECIALTY ROLL",desc:"Avocado, cucumber and marinated carrots topped with spicy king oyster krab dynamite.",taste:"Spicy, savory and creamy.",texture:"Cool vegetables underneath a rich mushroom-krab topping.",pairing:"Malbec",story:"This roll puts the spicy king oyster preparation up front and lets the cleaner vegetables underneath balance the richness."},
"royale-roll":{name:"Royale Roll",price:"20",image:img.specialty,category:"SPECIALTY ROLL",desc:"Avocado, cucumber and cream cheese topped with butter-poached vegan sckallop.",taste:"Buttery, creamy and savory.",texture:"Soft sckallop and cream cheese with crisp cucumber.",pairing:"Bushido Sake or Pinot Grigio",story:"Royale is one of the smoother, richer signatures, built around a soft sckallop topping and cool creamy center."},
"caterpillar-roll":{name:"Caterpillar Roll",price:"20",image:img.specialty,category:"SPECIALTY ROLL",desc:"Marinated eggplant and cucumber topped with avocado, spicy mayo and vegan eel sauce.",taste:"Sweet-savory with creamy heat.",texture:"Soft eggplant, crisp cucumber and smooth avocado.",pairing:"Amethyst in Bloom or Pinot Grigio",story:"A familiar sushi silhouette rebuilt entirely through plant-based ingredients."},
"baked-alaska":{name:"Baked Alaska",price:"21",image:img.specialty,category:"SPECIALTY ROLL",desc:"Cucumber and avocado topped with garlicky jackfruit salad, house sauces and GF panko.",taste:"Garlicky, creamy and savory.",texture:"Crunchy panko over soft jackfruit and avocado.",pairing:"Pinot Grigio",story:"Baked Alaska layers a cool roll base with a richer, textured top so every bite moves from crisp to creamy."},
"cali-roll":{name:"Cali Roll",price:"20",image:img.specialty,category:"SPECIALTY ROLL",desc:"Garlicky jackfruit salad over avocado and cucumber.",taste:"Garlicky, savory and fresh.",texture:"Tender jackfruit over crisp cucumber and soft avocado.",pairing:"Pinot Grigio",story:"The Cali takes the familiar California-roll idea and turns the jackfruit component into the headline."},
"rainbow-roll":{name:"Rainbow Roll",price:"22",image:img.specialty,category:"SPECIALTY ROLL",desc:"Krab, cucumber and avocado topped with toona, mango, unagi and avocado.",taste:"Sweet, savory, bright and fruit-forward.",texture:"Creamy avocado against crisp cucumber and layered toppings.",pairing:"Malbec",story:"A colorful House roll designed around contrast: fruit, umami and texture in one plate."},
"the-sky-is-the-limit":{name:"The Sky Is The Limit",price:"16",image:img.specialty,category:"SPECIALTY ROLL",desc:"King oyster mushroom, vegan cream cheese, avocado, cucumber and shiso.",taste:"Earthy, creamy and herbaceous.",texture:"Tender mushroom and avocado with crisp cucumber.",pairing:"Old Red Vine Zinfandel",story:"A quieter specialty roll where mushroom, creaminess and shiso carry the flavor rather than heavy sauce."},
"winter-roll":{name:"Winter Roll",price:"16",image:img.specialty,category:"SPECIALTY ROLL",desc:"Marinated sweet potato, GF panko and avocado with vegan eel sauce.",taste:"Sweet-savory and comforting.",texture:"Soft sweet potato and avocado with crisp panko.",pairing:"Pinot Grigio",story:"The Winter Roll is built around warmth and texture, using sweet potato as the center instead of seafood-style ingredients."},
"guava-rose-cheesecake":{name:"Guava Rose Cheesecake",price:"11",image:img.guava,category:"DESSERT",desc:"Fresh guava and creamy cashew base on a Celestial Chunk cookie crust.",taste:"Floral, fruity and creamy.",texture:"Smooth cashew filling over a firm cookie crust.",pairing:"Coffee or Riesling",story:"A bright tropical finish that keeps the dessert course feeling distinctly House."},
"vegan-tiramisu":{name:"Vegan Tiramisu",price:"10",image:img.tiramisu,category:"DESSERT",desc:"House-made vegan tiramisu with rich, balanced layers.",taste:"Coffee-forward, cocoa-rich and gently sweet.",texture:"Soft layered cream and cake.",pairing:"Espresso",story:"The familiar classic rebuilt without losing the reason people order tiramisu in the first place."},
"strawberry-matcha-tiramisu":{name:"Strawberry Matcha Tiramisu",price:"10",image:img.strawberry,category:"DESSERT",desc:"Vanilla layers, matcha ladyfingers and strawberries macerated in rosé.",taste:"Earthy matcha, vanilla sweetness and bright strawberry.",texture:"Soft layered tiramisu with juicy fruit.",pairing:"Tea",story:"A colorful remix that combines tea, fruit and dessert into one House finish."},
"passion-fruit-cheesecake":{name:"Passion Fruit Cheesecake",price:"10",image:img.passion,category:"DESSERT",desc:"Passion fruit and vanilla cheesecake sweetened with house-made syrup.",taste:"Tart tropical fruit balanced by creamy vanilla.",texture:"Silky cheesecake with a bright syrup finish.",pairing:"Riesling",story:"A sharper, brighter cheesecake for guests who want the last bite to wake the palate back up."}
};

export function generateStaticParams(){return Object.keys(items).map(slug=>({slug}))}

export default async function PlateDetail({params}){const {slug}=await params;const x=items[slug];if(!x)return notFound();return <main className="plateDetail">
<header className="plateDetailTop"><a href="/menu">← MENU</a><a href={orderUrl} target="_blank" rel="noreferrer">ORDER NOW ↗</a></header>
<section className="plateDetailHero"><figure><img src={x.image} alt={x.name+" at House of Vegano"}/></figure><div className="plateDetailCopy"><span>{x.category} · HOUSE OF VEGANO</span><h1>{x.name}<br/><em>AT THE HOUSE.</em></h1><b className="plateDetailPrice">{"$"+x.price}</b><p>{x.desc}</p><div className="plateDetailActions"><a href={orderUrl} target="_blank" rel="noreferrer">ORDER THIS PLATE ↗</a><a href="/menu">BACK TO MENU</a></div></div></section>
<section className="plateTaste"><span>WHAT IT’S LIKE</span><h2>TASTE.<br/>TEXTURE.<br/><em>WHY IT WORKS.</em></h2><div className="tasteGrid"><article><small>01 · TASTE</small><strong>THE FLAVOR</strong><p>{x.taste}</p></article><article><small>02 · TEXTURE</small><strong>THE BITE</strong><p>{x.texture}</p></article><article><small>03 · PAIRING</small><strong>DRINK WITH IT</strong><p>{x.pairing}</p></article></div></section>
<section className="plateStory"><div><span>THE HOUSE POINT OF VIEW</span><h2>MORE THAN<br/><em>A MENU LINE.</em></h2><p>{x.story}</p><p>The detail here is based on the dish’s listed ingredients and the way those ingredients work together. House of Vegano builds plant-based food around flavor first.</p><div className="plateDetailActions"><a href={orderUrl} target="_blank" rel="noreferrer">ORDER NOW ↗</a><a href="/menu">EXPLORE MORE PLATES</a></div></div><figure><img src={x.image} alt={x.name+" close view"}/></figure></section>
<footer className="plateDetailFooter"><span>HOUSE OF VEGANO</span><span>1990 CENTRAL AVE · ST. PETERSBURG</span><a href="/menu">EXPLORE MORE PLATES →</a></footer>
</main>}
