import {notFound} from "next/navigation";

const orderUrl="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes";

const items={
"still-i-rise":{name:"Still I Rise",price:"24",image:"https://static.spotapps.co/spots/e3/a4cf0cbd0545be875e5f25a082fa24/full",category:"SIGNATURE ROLL",desc:"Spicy king oyster krab and cucumber topped with scorched avocado, vegan caviar and butter-poached vegan lobstah.",taste:"Creamy, savory and gently spicy with a rich finish.",texture:"Tender mushroom krab, cool cucumber, silky avocado and buttery lobstah.",story:"A layered House signature built to move from freshness into richness without losing balance.",pairing:"Pinot Grigio"},
"adriana-vegano-sparkle-ii":{name:"Adriana “Vegano” Sparkle II",price:"24",image:"https://static.spotapps.co/spots/5e/2c1afb6a71456cae33a86586a70aa7/full",category:"SIGNATURE ROLL",desc:"Vegan sckallop, cucumber and avocado topped with house toona tartare and 24-karat gold sparkle.",taste:"Bright, creamy and luxurious with a clean ocean-inspired profile.",texture:"Soft sckallop, crisp cucumber, creamy avocado and silky toona tartare.",story:"One of the House’s showpieces—built to feel celebratory, polished and unmistakably Vegano.",pairing:"Riesling"},
"rainbow-roll":{name:"Rainbow Roll",price:"22",image:"https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full",category:"SIGNATURE ROLL",desc:"Krab, cucumber and avocado topped with toona, mango, unagi and avocado.",taste:"Sweet, savory, bright and fruit-forward.",texture:"Creamy avocado against crisp cucumber and layered toppings.",story:"A colorful House roll designed around contrast—fruit, umami and texture in one plate.",pairing:"Malbec"},
"the-burg":{name:"The Burg",price:"23",image:"https://static.spotapps.co/spots/1e/625e4f72784322b93a681619b32b35/full",category:"SIGNATURE ROLL",desc:"Eggplant, cucumber, tempura crumbs, torched avocado, lion’s mane, king oyster and vegan lobstah.",taste:"Smoky, rich and savory with a torched finish.",texture:"Crunch from tempura against tender mushrooms and soft avocado.",story:"Named with St. Pete energy in mind, The Burg leans into char, depth and the House’s mushroom-forward style.",pairing:"Old Red Vine Zinfandel"},
"volcano-roll":{name:"Volcano Roll",price:"23",image:"https://static.spotapps.co/spots/19/df68b6b6464223ab75475f858e73cf/full",category:"SIGNATURE ROLL",desc:"Avocado, carrot and cucumber beneath spicy lion’s mane seafood dynamite, vegan caviar and house sauces.",taste:"Hot, creamy and savory with a pronounced spicy finish.",texture:"Cool vegetables below a rich, saucy lion’s mane topping.",story:"The louder side of the House—built around heat, contrast and a dramatic top layer.",pairing:"Malbec"},
"caterpillar-roll":{name:"Caterpillar Roll",price:"20",image:"https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full",category:"SIGNATURE ROLL",desc:"Marinated eggplant and cucumber topped with avocado, spicy mayo and vegan eel sauce.",taste:"Sweet-savory with creamy heat.",texture:"Soft eggplant, crisp cucumber and a smooth avocado finish.",story:"A familiar sushi silhouette rebuilt entirely through plant-based ingredients.",pairing:"Amethyst in Bloom or Pinot Grigio"},
"sushi-gunkan":{name:"Sushi Gunkan",price:"12",image:"https://static.spotapps.co/spots/c9/8f265be6d64e4fa455a6e9421a0dd4/full",category:"SIGNATURE SIDE",desc:"Rice wrapped with nori. Choose three: lion’s mane, toona, lobstah or sckallops.",taste:"Savory and umami-forward with different toppings changing the character of each bite.",texture:"Tender rice, crisp nori and a soft composed topping.",story:"A tasting format that lets you move through several House flavors in one order.",pairing:"House sake"},
"edamame":{name:"Edamame",price:"8",image:"https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full",category:"SIGNATURE SIDE",desc:"Steamed edamame with gochujang garlic sesame dusting and Thai chili sauce.",taste:"Garlicky, sesame-rich and lightly spicy.",texture:"Tender beans with a seasoned exterior.",story:"A simple starter turned up with House heat and seasoning.",pairing:"Sapporo"},
"seaweed-salad":{name:"Seaweed Salad",price:"7",image:"https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full",category:"SIGNATURE SIDE",desc:"Wakame finished with sesame seeds.",taste:"Clean, lightly sweet and oceanic.",texture:"Cool, delicate and slightly crisp.",story:"The bright reset on the table—simple, cold and clean between richer dishes.",pairing:"Pinot Grigio"},
"nigiri-sampler":{name:"Nigiri Sampler",price:"12",image:"https://static.spotapps.co/spots/b9/4ffdf1e852484a90061289ba98cfc7/full",category:"NIGIRI",desc:"Unagi, spicy toona, sckallop and smoked salmon.",taste:"A range from smoky to spicy to savory.",texture:"Soft toppings over compact seasoned rice.",story:"A fast way to understand how the House reimagines nigiri across multiple ingredients.",pairing:"Bushido Sake"},
"smoked-salmon-nigiri":{name:"Smoked Salmon Nigiri",price:"12",image:"https://static.spotapps.co/spots/b9/4ffdf1e852484a90061289ba98cfc7/full",category:"NIGIRI",desc:"Vegan smoked salmon, spicy mayo, eel sauce, torched and finished with scallions.",taste:"Smoky, creamy and sweet-savory.",texture:"Silky topping with tender rice underneath.",story:"A single bite built to make the plant-based reinterpretation disappear behind flavor.",pairing:"Pinot Grigio"},
"nigiri-your-style":{name:"Nigiri · Choose Your Style",price:"6",image:"https://static.spotapps.co/spots/b9/4ffdf1e852484a90061289ba98cfc7/full",category:"NIGIRI",desc:"Choose spicy toona, unagi or sckallop truffle.",taste:"Choose spicy, sweet-savory or earthy-truffle.",texture:"Soft topping over seasoned rice.",story:"A focused one-piece format for building your own tasting sequence.",pairing:"Sake"},
"tom-kha-ramen":{name:"Tom Kha Ramen",price:"15",image:"https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full",category:"RAMEN",desc:"Chili lemongrass coconut broth with corn, scallions and vegan vork belly.",taste:"Creamy coconut, bright lemongrass and chili warmth.",texture:"Silky broth with noodles, corn and tender vegan vork belly.",story:"A comfort bowl that brings Thai-inspired aromatics into the House menu.",pairing:"Malbec"},
"hov-dumplings":{name:"HOV Dumplings",price:"10",image:"https://static.spotapps.co/spots/22/58ca1f2ae243adbe7beef55769878a/full",category:"DUMPLINGS",desc:"Soft, savory House dumplings built for sharing—or not sharing at all.",taste:"Savory, rich and deeply comforting.",texture:"Tender wrappers with a soft, juicy center.",story:"One of the dishes that best explains the House: familiar enough to crave immediately, different enough to remember.",pairing:"Amethyst in Bloom"},
"spicy-tahini-dumplings":{name:"Spicy Tahini Dumplings",price:"10",image:"https://static.spotapps.co/spots/22/58ca1f2ae243adbe7beef55769878a/full",category:"DUMPLINGS",desc:"House dumplings finished with spicy tahini richness and heat.",taste:"Nutty, creamy and spicy.",texture:"Soft dumplings coated in a rich tahini sauce.",story:"The House dumpling pushed toward deeper sesame flavor and a warmer finish.",pairing:"Riesling"},
"guava-rose-cheesecake":{name:"Guava Rose Cheesecake",price:"11",image:"https://static.spotapps.co/spots/81/548e0a2f0f4cbf86a8bbd67079d39c/full",category:"DESSERT",desc:"Fresh guava and creamy cashew base on a Celestial Chunk cookie crust.",taste:"Floral, fruity and creamy.",texture:"Smooth cashew filling over a firm cookie crust.",story:"A bright tropical finish that keeps the dessert course feeling distinctly House.",pairing:"Coffee or Riesling"},
"vegan-tiramisu":{name:"Vegan Tiramisu",price:"10",image:"https://static.spotapps.co/spots/56/031328c8ed48eabc685c378ce80859/full",category:"DESSERT",desc:"House-made vegan tiramisu with rich, balanced layers.",taste:"Coffee-forward, cocoa-rich and gently sweet.",texture:"Soft layered cream and cake.",story:"The familiar classic rebuilt without losing the reason people order tiramisu in the first place.",pairing:"Espresso"},
"strawberry-matcha-tiramisu":{name:"Strawberry Matcha Tiramisu",price:"10",image:"https://static.spotapps.co/spots/49/cf50f1e2c047ca85d908170f4fa18d/full",category:"DESSERT",desc:"Vanilla layers, matcha ladyfingers and strawberries macerated in rosé.",taste:"Earthy matcha, vanilla sweetness and bright strawberry.",texture:"Soft layered tiramisu with juicy fruit.",story:"A colorful remix that combines tea, fruit and dessert into one House finish.",pairing:"Tea"},
"passion-fruit-cheesecake":{name:"Passion Fruit Cheesecake",price:"10",image:"https://static.spotapps.co/spots/58/f6b5fa4b88425abcf44260cde9851b/full",category:"DESSERT",desc:"Passion fruit and vanilla cheesecake sweetened with house-made syrup.",taste:"Tart tropical fruit balanced by creamy vanilla.",texture:"Silky cheesecake with a bright syrup finish.",story:"A sharper, brighter cheesecake for guests who want the last bite to wake the palate back up.",pairing:"Riesling"}
};

export function generateStaticParams(){return Object.keys(items).map(slug=>({slug}))}

export default async function PlateDetail({params}){const {slug}=await params;const x=items[slug];if(!x)return notFound();return <main className="plateDetail">
<header className="plateDetailTop"><a href="/menu">← MENU</a><a href={orderUrl} target="_blank" rel="noreferrer">ORDER NOW ↗</a></header>
<section className="plateDetailHero"><figure><img src={x.image} alt={x.name+" at House of Vegano"}/></figure><div className="plateDetailCopy"><span>{x.category} · HOUSE OF VEGANO</span><h1>{x.name}<br/><em>AT THE HOUSE.</em></h1><b className="plateDetailPrice">{"$"+x.price}</b><p>{x.desc}</p><div className="plateDetailActions"><a href={orderUrl} target="_blank" rel="noreferrer">ORDER THIS PLATE ↗</a><a href="/menu">BACK TO MENU</a></div></div></section>
<section className="plateTaste"><span>WHAT IT’S LIKE</span><h2>TASTE.<br/>TEXTURE.<br/><em>WHY IT WORKS.</em></h2><div className="tasteGrid"><article><small>01 · TASTE</small><strong>THE FLAVOR</strong><p>{x.taste}</p></article><article><small>02 · TEXTURE</small><strong>THE BITE</strong><p>{x.texture}</p></article><article><small>03 · PAIRING</small><strong>DRINK WITH IT</strong><p>{x.pairing}</p></article></div></section>
<section className="plateStory"><div><span>THE HOUSE POINT OF VIEW</span><h2>MORE THAN<br/><em>A MENU LINE.</em></h2><p>{x.story}</p><p>House of Vegano builds plant-based food around flavor first. The point is not to imitate a conventional plate—it is to make the plate worth ordering on its own.</p><div className="plateDetailActions"><a href={orderUrl} target="_blank" rel="noreferrer">ORDER NOW ↗</a><a href="/">RETURN TO THE HOUSE</a></div></div><figure><img src={x.image} alt={x.name+" close view"}/></figure></section>
<footer className="plateDetailFooter"><span>HOUSE OF VEGANO</span><span>1990 CENTRAL AVE · ST. PETERSBURG</span><a href="/menu">EXPLORE MORE PLATES →</a></footer>
</main>}
