export const metadata={title:"Specials",description:"See current House of Vegano specials and lunch offers in St. Petersburg, Florida."};
export default function Specials(){return <main className="specialsPage">
<header className="specialsTop"><a href="/">← THE HOUSE</a><nav className="internalNav"><a href="/menu">MENU</a><a href="/menu/beverages">DRINKS</a><a href="/specials">SPECIALS</a><a href="/catering">CATERING</a><a href="/events">EVENTS</a></nav><a className="specialsOrder" href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER NOW ↗</a></header>
<section className="specialsHero"><div className="specialsHeroImage"><img src="https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full" alt="House of Vegano sushi spread"/></div><div className="specialsHeroShade"/><div className="specialsHeroCopy"><span>HOUSE OF VEGANO · ST. PETERSBURG</span><h1>LUNCH<br/><em>HITS DIFFERENT.</em></h1><p>Two classic rolls. One drink. Twenty-five dollars. Dine in, slow down for a minute, then get back to the day.</p></div></section>
<section className="specialsDeal"><div><span>THE CURRENT LUNCH SPECIAL</span><h2>2 ROLLS<br/>+ A DRINK<br/><em>$25.</em></h2></div><div className="specialsDealCopy"><p>Break up your day with a fresh, satisfying lunch from House of Vegano. Mix and match your favorite classic rolls or try something new.</p><div className="specialsDealTags"><b>2 CLASSIC ROLLS</b><b>1 DRINK</b><b>DINE-IN ONLY</b><b>11 AM–2 PM</b></div></div></section>
<section className="specialsDates"><article><span>MONDAY</span><strong>OCTOBER 5</strong><b>11:00 AM — 2:00 PM</b><p>Two classic rolls and a drink for $25. Dine in only.</p></article><article><span>THURSDAY</span><strong>OCTOBER 8</strong><b>11:00 AM — 2:00 PM</b><p>Two classic rolls and a drink for $25. Dine in only.</p></article><article><span>FRIDAY</span><strong>OCTOBER 9</strong><b>11:00 AM — 2:00 PM</b><p>Two classic rolls and a drink for $25. Dine in only.</p></article></section>
<section className="specialsBuild"><figure><img src="https://static.spotapps.co/spots/e3/a4cf0cbd0545be875e5f25a082fa24/full" alt="House of Vegano signature roll"/></figure><div><span>MAKE IT YOUR LUNCH</span><h2>PICK TWO.<br/><em>MIX IT UP.</em></h2><p>Go with two favorites, pair something familiar with something new, or split the table and trade bites. The point is a real House of Vegano lunch without turning the middle of the day into an afterthought.</p><a href="/menu/rolls">EXPLORE THE ROLLS →</a></div></section>
<section className="specialsCta"><span>READY FOR LUNCH?</span><h2>COME<br/>HUNGRY.</h2><div><a className="specialsHot" href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER NOW ↗</a><a href="/menu">SEE THE FULL MENU →</a></div></section>
<footer className="categoryFooter"><a href="/">HOUSE OF VEGANO</a><span>1990 CENTRAL AVE · ST. PETERSBURG</span><a href="/events">PARTIES + EVENTS →</a></footer>
</main>}