import Image from "next/image";
import {notFound} from "next/navigation";

const data={
"rolls":{eyebrow:"01 · THE ROLLS",title:"ROLLS.",line:"The art of the House.",image:"gold-signature-roll.png",second:"rainbow-roll-platter.png",copy:"Color, texture, precision and Thalia’s point of view—built into every roll.",rolls:true},
"signature-sides":{eyebrow:"02 · SIGNATURE SIDES",title:"SIDES.",line:"Never an afterthought.",image:"house-bowl.png",second:"sushi-table-spread.png",copy:"The supporting cast deserves its own spotlight. Small plates with full House energy.",theme:"sides"},
"beverages":{eyebrow:"03 · BEVERAGES",title:"DRINK.",line:"Pour something beautiful.",image:"new-090333.png",second:"dining-room-green-wall.png",copy:"Something bright, something sparkling, something made to sit beside the food.",theme:"drinks",drinks:true},
"desserts":{eyebrow:"04 · DESSERTS",title:"SWEET.",line:"The last bite matters.",image:"dessert-duo.png",second:"vegan-tiramisu.png",copy:"Tiramisu, cheesecake and sweet finishes that deserve their own course.",theme:"dessert",dessert:true},
"ramen":{eyebrow:"05 · RAMEN",title:"RAMEN.",line:"Deep comfort. House rules.",image:"ramen-house.png",second:"ramen-bowl.png",copy:"A bowl built for the moment when sushi is not enough.",theme:"ramen",ramen:true},
"dumplings":{eyebrow:"06 · HOUSE OBSESSION",title:"DUMPLINGS.",line:"You weren’t ready for these.",image:"signature-dumplings.png",second:"dumplings.png",copy:"Soft. Tender. Rich. Sweet. Savory. Some dishes need an explanation. These need another order.",obsession:true},
"test-kitchen":{eyebrow:"07 · THE TEST KITCHEN",title:"WHAT’S NEXT?",line:"Ideas before they become rules.",image:"thalia-chef-platter.png",second:"signature-roll-closeup.png",copy:"This is where Thalia experiments—limited ideas, new obsessions and dishes that may never sit still.",theme:"test",testKitchen:true},
"poke-bowl":{eyebrow:"08 · POKE BOWL",title:"THE BOWL.",line:"Built layer by layer.",image:"poke-bowl.png",second:"house-bowl.png",copy:"Color, texture and House flavor in every layer.",theme:"poke"},
"special-event":{eyebrow:"09 · SPECIAL EVENT",title:"MAKE IT YOURS.",line:"A table worth gathering around.",image:"dining-room-green-wall.png",second:"sushi-kraft-trays.png",copy:"Birthdays, celebrations, private gatherings and the food that makes people stay longer.",theme:"event"},
"lunch-special":{eyebrow:"10 · LUNCH SPECIAL",title:"MIDDAY.",line:"The House, for lunch.",image:"sushi-board-signatures.png",second:"avocado-signature-roll.png",copy:"A reason to make lunch the best part of the day. Current availability and pricing are confirmed when ordering.",theme:"lunch"}
};
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}))}
export default async function Category({params}){const {slug}=await params;const d=data[slug];if(!d)return notFound();return <main className="categoryExperience">
<header className="categoryTop"><a href="/">← THE HOUSE</a><a href="/menu">FULL MENU</a><a href="https://www.houseofvegano.com/" target="_blank" rel="noreferrer">ORDER NOW ↗</a></header>
<section className="categoryHero"><Image src={"/images/"+d.image} alt={d.title+" at House of Vegano"} fill priority sizes="100vw"/><div className="categoryShade"/><div className="categoryHeroCopy"><p>{d.eyebrow}</p><h1>{d.title}</h1><em>{d.line}</em></div></section>
<section className="categoryStatement"><span>HOUSE OF VEGANO · ST. PETERSBURG</span><h2>{d.copy}</h2></section>{d.drinks&&<><section className="drinkEditorial"><figure><Image src="/images/new-090333.png" alt="House of Vegano beverage" fill sizes="52vw"/></figure><div><span>THE HOUSE POUR · 03</span><h2>BRIGHT.<br/>FLORAL.<br/><em>BUILT TO PAIR.</em></h2><p>Drinks at the House are part of the meal—not an afterthought. Start with something vivid, move into sake or wine, or finish with coffee.</p><div className="drinkFeature"><small>HOUSE SIGNATURE</small><strong>AMETHYST IN BLOOM</strong><p>House-blend kombucha with lavender, lemongrass, ginger and butterfly pea blossom. The menu pairs it with rolls and appetizers.</p></div></div></section>
<section className="drinkPairings"><div className="drinkPairingIntro"><span>POUR WITH PURPOSE</span><h2>THE<br/><em>PAIRING TABLE.</em></h2><p>The House menu already tells a pairing story. We brought that logic forward so guests can choose the drink and the dish together.</p></div><div className="drinkPairingGrid">
<article><img src="https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full" alt="House of Vegano ramen"/><div><small>MALBEC</small><strong>HOUSE RAMEN</strong><p>Rich red fruit and earth against the warmth and depth of the bowl.</p><a href="/menu/ramen">PAIR WITH RAMEN →</a></div></article>
<article><img src="https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full" alt="House of Vegano Rainbow Roll"/><div><small>PINOT GRIGIO</small><strong>RAINBOW + BAKED ALASKA</strong><p>Crisp citrus and stone-fruit character with bright, layered rolls.</p><a href="/menu/rolls">PAIR WITH ROLLS →</a></div></article>
<article><img src="/images/vegan-tiramisu.png" alt="House of Vegano dessert"/><div><small>RIESLING</small><strong>THE SWEET FINISH</strong><p>Fresh fruit and mineral character alongside the dessert course.</p><a href="/menu/desserts">PAIR WITH DESSERT →</a></div></article>
</div></section>
<section className="drinkSpectrum"><div><span>BEYOND THE POUR</span><h2>SAKE.<br/>WINE.<br/>COFFEE.<br/><em>HOUSE.</em></h2><p>From yuzu sake and crisp beer to espresso drinks and tea, the beverage menu can carry you from the first roll through the final bite.</p><a href="https://www.houseofvegano.com/st-petersburg-downtown-st-petersburg-house-of-vegano-drink-menu" target="_blank" rel="noreferrer">SEE THE CURRENT DRINK MENU →</a></div><figure><Image src="/images/dining-room-green-wall.png" alt="House of Vegano dining room" fill sizes="50vw"/></figure></section>
<section className="drinkClose"><span>HOUSE OF VEGANO · BEVERAGES</span><h2>DON’T JUST<br/>ORDER A DRINK.<br/><em>BUILD THE MEAL.</em></h2><a href="https://www.houseofvegano.com/" target="_blank" rel="noreferrer">ORDER FROM THE HOUSE →</a></section></>{d.testKitchen&&<><section className="testEditorial"><div className="testPortrait"><Image src="/images/thalia-chef-platter.png" alt="Thalia Tatham with House of Vegano creations" fill sizes="55vw"/></div><div className="testWords"><span>THE TEST KITCHEN · 07</span><h2>NO<br/>RULES<br/><em>YET.</em></h2><p>Before a dish becomes part of the House, it gets to be an idea. This is where Thalia experiments.</p></div></section><section className="testExperiment"><Image src="/images/signature-roll-closeup.png" alt="House of Vegano Test Kitchen creation" fill sizes="100vw"/><div><small>EXPERIMENT · TASTE · DECIDE · REPEAT</small><strong>WHAT<br/>HAPPENS<br/><em>NEXT?</em></strong></div></section></>}{d.dessert&&<><section className="dessertEditorial"><div><span>THE LAST COURSE · 04</span><h2>SAVE<br/><em>ROOM.</em></h2><p>The ending should be every bit as memorable as the first bite. House of Vegano treats dessert like its own destination—creamy, layered, bright and worth staying for.</p><div className="dessertTags"><b>CREAMY</b><b>BRIGHT</b><b>DECADENT</b><b>HOUSE FINISH</b></div></div><figure><Image src="/images/vegan-tiramisu.png" alt="House of Vegano vegan tiramisu" fill sizes="55vw"/></figure></section>
<section className="dessertFeatureGrid"><article className="dessertFeature dessertFeatureTall"><img src="/images/dessert-duo.png" alt="House of Vegano cheesecake desserts"/><div><small>CHEESECAKE</small><strong>GUAVA ROSE</strong><p>Fresh guava, creamy cashew base and a celestial chunk cookie foundation.</p></div></article><article className="dessertFeature"><img src="/images/vegan-tiramisu.png" alt="House of Vegano vegan tiramisu"/><div><small>TIRAMISU</small><strong>THE CLASSIC FINISH</strong><p>A from-scratch signature built around richness, balance and a proper last bite.</p></div></article><article className="dessertFeature"><img src="/images/orange-dessert.png" alt="House of Vegano tropical cheesecake dessert"/><div><small>CHEESECAKE</small><strong>PASSION FRUIT</strong><p>Tropical fruit and vanilla with a house-made syrup finish.</p></div></article></section>
<section className="dessertStory"><div><span>THE SWEET SIDE OF THE HOUSE</span><h2>NOT AN<br/>AFTERTHOUGHT.<br/><em>THE FINALE.</em></h2><p>The menu also includes a Strawberry Matcha Tiramisu with vanilla layers, matcha-flavored ladyfingers and strawberries macerated in rosé wine.</p><a href="https://www.houseofvegano.com/st-petersburg-downtown-st-petersburg-house-of-vegano-food-menu" target="_blank" rel="noreferrer">SEE THE CURRENT DESSERT MENU →</a></div><figure><Image src="/images/dessert-duo.png" alt="House of Vegano sweet finish" fill sizes="50vw"/></figure></section>
<section className="dessertPairing"><div><span>ONE MORE THING</span><h2>STAY FOR<br/><em>DESSERT.</em></h2><p>The official drink menu pairs Riesling with all of the desserts, giving the last course its own pairing moment instead of treating it like an add-on.</p><a href="/menu/beverages">EXPLORE THE DRINKS →</a></div><div className="dessertPairingCard"><img src="/images/new-090333.png" alt="House of Vegano beverage"/><div><small>PAIR THE LAST COURSE</small><strong>RIESLING + SWEET FINISH</strong><a href="/menu/beverages">BUILD THE PAIRING →</a></div></div></section>
<section className="dessertClose"><span>HOUSE OF VEGANO · DESSERTS</span><h2>THE LAST BITE<br/>SHOULD STILL<br/><em>SURPRISE YOU.</em></h2><a href="https://www.houseofvegano.com/" target="_blank" rel="noreferrer">ORDER FROM THE HOUSE →</a></section></>}{d.ramen&&<><section className="ramenEditorial"><figure><img className="officialPhoto" src="https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full" alt="House of Vegano Tom Kha ramen"/></figure><div><span>THE BOWL · 05</span><h2>DEEP.<br/>WARM.<br/><em>HOUSE.</em></h2><p>Ramen at House of Vegano is built for the moment when you want something slower, warmer and completely absorbing.</p><div className="ramenTags"><b>LEMONGRASS</b><b>COCONUT</b><b>CHILI</b><b>COMFORT</b></div></div></section>
<section className="ramenBuild"><div><span>WHAT MAKES THE BOWL</span><h2>LAYERS<br/>OF <em>COMFORT.</em></h2><p>The experience starts with the broth and builds outward—aroma, richness, heat, vegetables and texture working together in one bowl.</p></div><ol><li><b>01</b><strong>THE BROTH</strong><p>Chili, lemongrass and coconut create a base that is bright, creamy and deeply aromatic.</p></li><li><b>02</b><strong>THE BODY</strong><p>Noodles, corn and scallions make the bowl substantial without losing the freshness underneath.</p></li><li><b>03</b><strong>THE FINISH</strong><p>Vegan vork belly and heat bring the richness and contrast that turn it from soup into a full House moment.</p></li></ol></section>
<section className="ramenMoment"><div><span>TOM KHA RAMEN</span><strong>STAY<br/><em>A WHILE.</em></strong><p>Warm enough to slow you down. Bold enough to keep you thinking about it after you leave.</p></div><img className="officialPhoto" src="https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full" alt="House of Vegano Tom Kha ramen"/></section>
<section className="ramenPairing"><div className="ramenPairingCopy"><span>MAKE IT A MEAL</span><h2>START<br/>BRIGHT.<br/><em>FINISH WARM.</em></h2><p>Pair the bowl with something crisp or shareable first—dumplings, sushi or a lighter side—then let the ramen own the middle of the table.</p><a href="/menu">EXPLORE THE FULL MENU →</a></div><div className="ramenPairingCards"><article className="ramenPairCard ramenPairCardDumplings"><img src="https://static.spotapps.co/spots/22/58ca1f2ae243adbe7beef55769878a/full" alt="House of Vegano dumplings"/><div><strong>DUMPLINGS</strong><p>Soft, saucy and made for sharing before the bowl arrives.</p><a href="/menu/dumplings">ENTER THE DUMPLINGS →</a></div></article><article className="ramenPairCard ramenPairCardRolls"><img src="https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full" alt="House of Vegano signature rolls"/><div><strong>SIGNATURE ROLLS</strong><p>Color and contrast before the warmth of the ramen.</p><a href="/menu/rolls">EXPLORE THE ROLLS →</a></div></article></div></section>
<section className="ramenClose"><span>HOUSE OF VEGANO · RAMEN</span><h2>NOT JUST A BOWL.<br/><em>A RESET.</em></h2><a href="https://www.houseofvegano.com/" target="_blank" rel="noreferrer">ORDER FROM THE HOUSE →</a></section></>}{d.rolls&&<><section className="rollsEditorial"><div className="rollsWord">ROLL<br/><em>WITH IT.</em></div><figure><img className="officialPhoto" src="https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full" alt="House of Vegano signature sushi board"/></figure><div className="rollsNote"><span>THE HOUSE · 01</span><p>Not imitation. Not compromise. A different idea of what sushi can be—built around mushrooms, vegetables, fruit, sauces, heat and texture.</p><div className="rollsTags"><b>COLOR</b><b>TEXTURE</b><b>HEAT</b><b>UMAMI</b></div></div></section>
<section className="rollsStrip"><img className="officialPhoto" src="https://static.spotapps.co/spots/e3/a4cf0cbd0545be875e5f25a082fa24/full" alt="House of Vegano Still I Rise roll"/><div>COLOR · TEXTURE · PRECISION · HOUSE</div></section>
<section className="rollsPhilosophy"><div><span>THE HOUSE METHOD</span><h2>BUILD THE<br/><em>BITE.</em></h2><p>Every signature roll is designed as a complete experience. Richness needs acid. Softness needs crunch. Heat needs something cool beside it. The roll works when every element has a job.</p></div><div className="rollsSteps"><article><b>01</b><strong>FOUNDATION</strong><p>Rice, nori, vegetables and the structure that keeps the bite together.</p></article><article><b>02</b><strong>TEXTURE</strong><p>King oyster, lion’s mane, avocado, crisp crumbs and layered contrast.</p></article><article><b>03</b><strong>FINISH</strong><p>House sauces, heat, torched elements, caviar and color that make the roll unmistakably Vegano.</p></article></div></section>
<section className="rollsSignatures"><div className="rollsSignaturesIntro"><span>SIGNATURES TO KNOW</span><h2>START<br/>HERE.</h2><p>Four rolls that tell the House story from different directions.</p></div><div className="rollsCards"><article><img src="https://static.spotapps.co/spots/5e/2c1afb6a71456cae33a86586a70aa7/full" alt="Adriana Vegano Sparkle II roll"/><div><span>01</span><h3>ADRIANA “VEGANO” SPARKLE II</h3><p>Vegan sckallop, cucumber and avocado topped with house toona tartare and 24-karat gold sparkle.</p><strong>SHOWSTOPPER</strong></div></article><article><img src="https://static.spotapps.co/spots/19/df68b6b6464223ab75475f858e73cf/full" alt="Spicy Tuna roll"/><div><span>02</span><h3>SPICY TOONA</h3><p>Marinated tomato toona, avocado and cucumber with spicy mayo.</p><strong>BRIGHT + SPICY</strong></div></article><article><img src="https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full" alt="Rainbow Roll"/><div><span>03</span><h3>RAINBOW ROLL</h3><p>Krab, cucumber and avocado topped with toona, mango, unagi and avocado.</p><strong>COLOR + CONTRAST</strong></div></article><article><img src="https://static.spotapps.co/spots/1e/625e4f72784322b93a681619b32b35/full" alt="The Burg roll"/><div><span>04</span><h3>THE BURG</h3><p>Eggplant, cucumber, tempura crumbs, torched avocado, lion’s mane, king oyster and vegan lobstah.</p><strong>RICH + TORCHED</strong></div></article></div></section>
<section className="rollsClose"><span>HOUSE OF VEGANO · ST. PETERSBURG</span><h2>THE ROLL ISN’T<br/>THE ALTERNATIVE.<br/><em>IT’S THE REASON.</em></h2><a href="/menu">SEE THE FULL MENU →</a></section></>}{d.obsession&&<><section className="dumplingEditorial"><div className="dumplingNumber">01</div><div><p>THE HOUSE OBSESSION</p><h2>SOFT.<br/>TENDER.<br/><em>RIDICULOUS.</em></h2></div><figure><Image src="/images/dumplings-bowl.png" alt="House of Vegano dumplings" fill sizes="45vw"/></figure></section><section className="dumplingQuote"><div>★★★★★</div><blockquote>“Just had the best dumplings ever. Who knew they were vegan?”</blockquote><span>GREGGORY BUTLER · GOOGLE REVIEW</span></section></>}
{d.theme&&<section className={"categorySignature "+d.theme}><span>{d.eyebrow}</span><strong>{d.theme==="dessert"?"SAVE ROOM.":d.theme==="ramen"?"STAY A WHILE.":d.theme==="drinks"?"POUR. SIP. STAY.":d.theme==="test"?"NO RULES YET.":d.theme==="event"?"GATHER HERE.":d.theme==="lunch"?"MAKE LUNCH COUNT.":d.theme==="poke"?"BUILD THE BOWL.":"SMALL PLATES. BIG ENERGY."}</strong></section>}<section className="categoryDiptych"><figure><Image src={"/images/"+d.second} alt={d.title+" House of Vegano"} fill sizes="60vw"/></figure><div><small>THALIA’S HOUSE</small><h2>COME<br/>TASTE<br/><em>WHY.</em></h2><p>Plant-based. Chef-driven. Made to be remembered.</p><a href="https://www.houseofvegano.com/" target="_blank" rel="noreferrer">ORDER FROM THE HOUSE →</a></div></section>
<footer className="categoryFooter"><a href="/">HOUSE OF VEGANO</a><span>1990 CENTRAL AVE · ST. PETERSBURG</span><a href="/menu">EXPLORE THE FULL MENU →</a></footer>
<a className="mobileOrder" href="https://www.houseofvegano.com/" target="_blank" rel="noreferrer">ORDER NOW ↗</a>
</main>}