import Image from "next/image";
import {notFound} from "next/navigation";

const data={
"rolls":{eyebrow:"01 · THE ROLLS",title:"ROLLS.",line:"The art of the House.",image:"https://static.spotapps.co/spots/e3/a4cf0cbd0545be875e5f25a082fa24/full",second:"https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full",copy:"Color, texture, precision and Thalia’s point of view—built into every roll.",rolls:true},
"signature-sides":{eyebrow:"02 · SIGNATURE SIDES",title:"SIDES.",line:"Never an afterthought.",image:"https://static.spotapps.co/spots/c9/8f265be6d64e4fa455a6e9421a0dd4/full",second:"https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full",copy:"The supporting cast deserves its own spotlight. Small plates with full House energy.",theme:"sides",sides:true},
"beverages":{eyebrow:"03 · BEVERAGES",title:"DRINK.",line:"Pour something beautiful.",image:"https://static.spotapps.co/spots/ce/a90a531f1f4aaaac27e6b2db34e2fe/full",second:"https://static.spotapps.co/spots/9a/152f3951a2457b89a719060c837ee7/full",copy:"Something bright, something sparkling, something made to sit beside the food.",theme:"drinks",drinks:true},
"desserts":{eyebrow:"04 · DESSERTS",title:"SWEET.",line:"The last bite matters.",image:"https://static.spotapps.co/spots/56/031328c8ed48eabc685c378ce80859/full",second:"https://static.spotapps.co/spots/56/031328c8ed48eabc685c378ce80859/full",copy:"Tiramisu, cheesecake and sweet finishes that deserve their own course.",theme:"dessert",dessert:true},
"ramen":{eyebrow:"05 · RAMEN",title:"RAMEN.",line:"Deep comfort. House rules.",image:"https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full",second:"https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full",copy:"A bowl built for the moment when sushi is not enough.",theme:"ramen",ramen:true},
"dumplings":{eyebrow:"06 · HOUSE OBSESSION",title:"DUMPLINGS.",line:"You weren’t ready for these.",image:"https://static.spotapps.co/spots/22/58ca1f2ae243adbe7beef55769878a/full",second:"https://static.spotapps.co/spots/22/58ca1f2ae243adbe7beef55769878a/full",copy:"Soft. Tender. Rich. Sweet. Savory. Some dishes need an explanation. These need another order.",obsession:true},
"test-kitchen":{eyebrow:"07 · THE TEST KITCHEN",title:"WHAT’S NEXT?",line:"Ideas before they become rules.",image:"thalia-chef-platter.png",second:"https://static.spotapps.co/spots/5e/2c1afb6a71456cae33a86586a70aa7/full",copy:"This is where Thalia experiments—limited ideas, new obsessions and dishes that may never sit still.",theme:"test",testKitchen:true},
"poke-bowl":{eyebrow:"08 · POKE BOWL",title:"THE BOWL.",line:"Built layer by layer.",image:"https://static.spotapps.co/spots/c9/8f265be6d64e4fa455a6e9421a0dd4/full",second:"https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full",copy:"Color, texture and House flavor in every layer.",theme:"poke"},
"special-event":{eyebrow:"09 · SPECIAL EVENT",title:"MAKE IT YOURS.",line:"A table worth gathering around.",image:"https://static.spotapps.co/spots/27/ac6ef4152949d0b8ecdfbaa1c57ba3/wide_medium",second:"https://static.spotapps.co/spots/3f/d404bdb5bb4092aba3a73542386cbb/wide_medium",copy:"Birthdays, celebrations, private gatherings and the food that makes people stay longer.",theme:"event"},
"lunch-special":{eyebrow:"10 · LUNCH SPECIAL",title:"MIDDAY.",line:"The House, for lunch.",image:"https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full",second:"https://static.spotapps.co/spots/e3/a4cf0cbd0545be875e5f25a082fa24/full",copy:"A reason to make lunch the best part of the day. Current availability and pricing are confirmed when ordering.",theme:"lunch"}
};
const roomItems={
"rolls":[
 {slug:"still-i-rise",name:"Still I Rise",price:"24",image:"https://static.spotapps.co/spots/e3/a4cf0cbd0545be875e5f25a082fa24/full",desc:"Spicy king oyster krab and cucumber topped with scorched avocado, vegan caviar and butter-poached vegan lobstah."},
 {slug:"adriana-vegano-sparkle-ii",name:"Adriana “Vegano” Sparkle II",price:"24",image:"https://static.spotapps.co/spots/5e/2c1afb6a71456cae33a86586a70aa7/full",desc:"Vegan sckallop, cucumber and avocado topped with house toona tartare and 24-karat gold sparkle."},
 {slug:"rainbow-roll",name:"Rainbow Roll",price:"22",image:"https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full",desc:"Krab, cucumber and avocado topped with toona, mango, unagi and avocado."},
 {slug:"the-burg",name:"The Burg",price:"23",image:"https://static.spotapps.co/spots/1e/625e4f72784322b93a681619b32b35/full",desc:"Eggplant, cucumber, tempura crumbs, torched avocado, lion’s mane, king oyster and vegan lobstah."},
 {slug:"volcano-roll",name:"Volcano Roll",price:"23",image:"https://static.spotapps.co/spots/19/df68b6b6464223ab75475f858e73cf/full",desc:"Avocado, carrot and cucumber beneath spicy lion’s mane seafood dynamite, vegan caviar and house sauces."},
 {slug:"caterpillar-roll",name:"Caterpillar Roll",price:"20",image:"https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full",desc:"Marinated eggplant and cucumber topped with avocado, spicy mayo and vegan eel sauce."}
],
"signature-sides":[
 {slug:"sushi-gunkan",name:"Sushi Gunkan",price:"12",image:"https://static.spotapps.co/spots/c9/8f265be6d64e4fa455a6e9421a0dd4/full",desc:"Rice wrapped with nori. Choose three: lion’s mane, toona, lobstah or sckallops."},
 {slug:"edamame",name:"Edamame",price:"8",image:"https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full",desc:"Steamed edamame with gochujang garlic sesame dusting and Thai chili sauce."},
 {slug:"seaweed-salad",name:"Seaweed Salad",price:"7",image:"https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full",desc:"Wakame finished with sesame seeds."},
 {slug:"nigiri-sampler",name:"Nigiri Sampler",price:"12",image:"https://static.spotapps.co/spots/b9/4ffdf1e852484a90061289ba98cfc7/full",desc:"Unagi, spicy toona, sckallop and smoked salmon."},
 {slug:"smoked-salmon-nigiri",name:"Smoked Salmon Nigiri",price:"12",image:"https://static.spotapps.co/spots/b9/4ffdf1e852484a90061289ba98cfc7/full",desc:"Vegan smoked salmon, spicy mayo, eel sauce, torched and finished with scallions."},
 {slug:"nigiri-your-style",name:"Nigiri · Choose Your Style",price:"6",image:"https://static.spotapps.co/spots/b9/4ffdf1e852484a90061289ba98cfc7/full",desc:"Choose spicy toona, unagi or sckallop truffle."}
],
"ramen":[
 {slug:"tom-kha-ramen",name:"Tom Kha Ramen",price:"15",image:"https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full",desc:"Chili lemongrass coconut broth with corn, scallions and vegan vork belly."}
],
"dumplings":[
 {slug:"hov-dumplings",name:"HOV Dumplings",price:"10",image:"https://static.spotapps.co/spots/22/58ca1f2ae243adbe7beef55769878a/full",desc:"Soft, savory House dumplings built for sharing—or not sharing at all."},
 {slug:"spicy-tahini-dumplings",name:"Spicy Tahini Dumplings",price:"10",image:"https://static.spotapps.co/spots/22/58ca1f2ae243adbe7beef55769878a/full",desc:"House dumplings finished with spicy tahini richness and heat."}
],
"desserts":[
 {slug:"guava-rose-cheesecake",name:"Guava Rose Cheesecake",price:"11",image:"https://static.spotapps.co/spots/81/548e0a2f0f4cbf86a8bbd67079d39c/full",desc:"Fresh guava and creamy cashew base on a Celestial Chunk cookie crust."},
 {slug:"vegan-tiramisu",name:"Vegan Tiramisu",price:"10",image:"https://static.spotapps.co/spots/56/031328c8ed48eabc685c378ce80859/full",desc:"House-made vegan tiramisu with rich, balanced layers."},
 {slug:"strawberry-matcha-tiramisu",name:"Strawberry Matcha Tiramisu",price:"10",image:"https://static.spotapps.co/spots/49/cf50f1e2c047ca85d908170f4fa18d/full",desc:"Vanilla layers, matcha ladyfingers and strawberries macerated in rosé."},
 {slug:"passion-fruit-cheesecake",name:"Passion Fruit Cheesecake",price:"10",image:"https://static.spotapps.co/spots/58/f6b5fa4b88425abcf44260cde9851b/full",desc:"Passion fruit and vanilla cheesecake sweetened with house-made syrup."}
]
};
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}))}
export default async function Category({params}){const {slug}=await params;const d=data[slug];if(!d)return notFound();return <main className="categoryExperience">
<header className="categoryTop"><a href="/">← THE HOUSE</a><nav className="internalNav"><a href="/menu">MENU</a><a href="/menu/beverages">DRINKS</a><a href="/specials">SPECIALS</a><a href="/catering">CATERING</a><a href="/events">EVENTS</a></nav><a href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER NOW ↗</a></header>
<section className="categoryHero">{d.image.startsWith("http")?<img className="categoryRemotePhoto" src={d.image} alt={d.title+" at House of Vegano"}/>:<Image src={"/images/"+d.image} alt={d.title+" at House of Vegano"} fill priority sizes="100vw"/>}<div className="categoryShade"/><div className="categoryHeroCopy"><p>{d.eyebrow}</p><h1>{d.title}</h1><em>{d.line}</em></div></section>
<section className="categoryStatement"><span>HOUSE OF VEGANO · ST. PETERSBURG</span><h2>{d.copy}</h2></section>{roomItems[slug]&&<section className="roomPlateMenu"><div className="roomPlateIntro"><span>CHOOSE YOUR PLATE</span><h2>SEE IT.<br/><em>OPEN IT.</em><br/>KNOW IT.</h2><p>Each plate opens into its own room with ingredients, flavor, texture, pairing notes and the story behind the dish.</p></div><div className="roomPlateGrid">{roomItems[slug].map((x,i)=><article className="roomPlateCard" key={x.slug}><a className="roomPlateImage" href={"/menu/item/"+x.slug}><img src={x.image} alt={x.name+" at House of Vegano"}/></a><div className="roomPlateBody"><small>{String(i+1).padStart(2,"0")} · {d.title.replace(".","")}</small><div className="roomPlateTitle"><h3>{x.name}</h3><b>{"$"+x.price}</b></div><p>{x.desc}</p><div className="roomPlateActions"><a href={"/menu/item/"+x.slug}>SEE DETAILS</a><a href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER NOW</a></div></div></article>)}</div></section>}{d.sides&&<><section className="sidesEditorial"><div className="sidesEditorialCopy"><span>THE SUPPORTING CAST · 02</span><h2>START<br/>WITH<br/><em>SOMETHING.</em></h2><p>The sides at House of Vegano are not filler between rolls. They bring heat, crunch, umami, acid and texture to the table before the main event even starts.</p><div className="sidesTags"><b>SHAREABLE</b><b>TEXTURE-FIRST</b><b>HOUSE FLAVOR</b><b>PLANT-BASED</b></div></div><figure><img className="officialPhoto" src="https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full" alt="House of Vegano sides and sushi spread"/></figure></section>
<section className="sidesMenu"><div className="sidesMenuIntro"><span>FROM THE CURRENT MENU</span><h2>SMALL PLATES.<br/><em>FULL PERSONALITY.</em></h2><p>Build the table around a few things worth passing around. These are the current side and nigiri choices featured on the House menu.</p></div><div className="sidesMenuGrid">
<article><small>01 · HOUSE STARTER</small><strong>SUSHI GUNKAN</strong><b>$12</b><p>Rice wrapped with nori. Choose three: lion’s mane, toona, lobstah or sckallops.</p></article>
<article><small>02 · HEAT + CRUNCH</small><strong>EDAMAME</strong><b>$8</b><p>Steamed edamame with gochujang garlic sesame dusting and Thai chili sauce.</p></article>
<article><small>03 · BRIGHT + CLEAN</small><strong>SEAWEED SALAD</strong><b>$7</b><p>Wakame finished with sesame seeds.</p></article>
<article><small>04 · TASTE AROUND</small><strong>NIGIRI SAMPLER</strong><b>$12</b><p>Unagi, spicy toona, sckallop and smoked salmon.</p></article>
</div></section>
<section className="sidesSpotlight"><figure><img className="sidesChefPhoto" src="/images/thalia-chef-serious.webp?v=20261006b" alt="Thalia in chef attire"/></figure><div><span>NIGIRI · HOUSE STYLE</span><h2>ONE<br/>BITE.<br/><em>ALL IN.</em></h2><p>Smoked salmon nigiri is finished with spicy mayo, eel sauce, a torch and scallions. Or keep it simple and choose spicy toona, unagi or sckallop truffle.</p><div className="sidesMiniMenu"><div><strong>SMOKED SALMON NIGIRI</strong><b>$12</b></div><div><strong>NIGIRI · CHOOSE YOUR STYLE</strong><b>$6</b></div></div><a href="/menu">SEE THE FULL MENU →</a></div></section>
<section className="sidesBuild"><div><span>BUILD THE TABLE</span><h2>ROLLS ARE THE HEADLINE.<br/><em>SIDES SET THE RHYTHM.</em></h2></div><ol><li><b>01</b><strong>START BRIGHT.</strong><p>Seaweed salad or edamame wakes up the table.</p></li><li><b>02</b><strong>ADD TEXTURE.</strong><p>Gunkan and nigiri bring another shape, temperature and bite.</p></li><li><b>03</b><strong>THEN GO BIG.</strong><p>Move into signature rolls, dumplings or ramen once the table is already alive.</p></li></ol></section>
<section className="sidesClose"><span>HOUSE OF VEGANO · SIGNATURE SIDES</span><h2>DON’T CALL THEM<br/><em>EXTRAS.</em></h2><div><a href="/menu">EXPLORE THE FULL MENU →</a><a href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER FROM THE HOUSE ↗</a></div></section></>}{d.drinks&&<><section className="drinkEditorial"><figure><img className="officialPhoto" src="https://static.spotapps.co/spots/ce/a90a531f1f4aaaac27e6b2db34e2fe/full" alt="House of Vegano Amethyst In Bloom"/></figure><div><span>THE HOUSE POUR · 03</span><h2>BRIGHT.<br/>FLORAL.<br/><em>BUILT TO PAIR.</em></h2><p>Drinks at the House are part of the meal—not an afterthought. Start with something vivid, move into sake or wine, or finish with coffee.</p><div className="drinkFeature"><small>HOUSE SIGNATURE</small><strong>AMETHYST IN BLOOM</strong><p>House-blend kombucha with lavender, lemongrass, ginger and butterfly pea blossom. The menu pairs it with rolls and appetizers.</p></div></div></section>
<section className="drinkPairings"><div className="drinkPairingIntro"><span>POUR WITH PURPOSE</span><h2>THE<br/><em>PAIRING TABLE.</em></h2><p>The House menu already tells a pairing story. We brought that logic forward so guests can choose the drink and the dish together.</p></div><div className="drinkPairingGrid">
<article><img src="https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full" alt="House of Vegano ramen"/><div><small>MALBEC</small><strong>HOUSE RAMEN</strong><p>Rich red fruit and earth against the warmth and depth of the bowl.</p><a href="/menu/ramen">PAIR WITH RAMEN →</a></div></article>
<article><img src="https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full" alt="House of Vegano Rainbow Roll"/><div><small>PINOT GRIGIO</small><strong>RAINBOW + BAKED ALASKA</strong><p>Crisp citrus and stone-fruit character with bright, layered rolls.</p><a href="/menu/rolls">PAIR WITH ROLLS →</a></div></article>
<article><img src="https://static.spotapps.co/spots/49/cf50f1e2c047ca85d908170f4fa18d/full" alt="House of Vegano dessert"/><div><small>RIESLING</small><strong>THE SWEET FINISH</strong><p>Fresh fruit and mineral character alongside the dessert course.</p><a href="/menu/desserts">PAIR WITH DESSERT →</a></div></article>
</div></section>
<section className="drinkSpectrum"><div><span>BEYOND THE POUR</span><h2>SAKE.<br/>WINE.<br/>COFFEE.<br/><em>HOUSE.</em></h2><p>From yuzu sake and crisp beer to espresso drinks and tea, the beverage menu can carry you from the first roll through the final bite.</p><a href="/menu/beverages">SEE THE CURRENT DRINK MENU →</a></div><div className="drinkBottleGrid"><article><img src="https://static.spotapps.co/spots/76/41197b13f34e46aec9ef2d92c28804/full" alt="Bushido Sake"/><span>BUSHIDO SAKE</span></article><article><img src="https://static.spotapps.co/spots/61/5c961dc56643dba25888779e183fc8/full" alt="Wakaze Yuzu Sake"/><span>WAKAZE YUZU</span></article><article><img src="https://static.spotapps.co/spots/28/b1b903c8704971872e497e3ee8e51e/full" alt="Gabbiano Pinot Grigio"/><span>PINOT GRIGIO</span></article><article><img src="https://static.spotapps.co/spots/a4/b963ba5e7e4e9d86717e64b5e96c9a/full" alt="August Kesseler Riesling"/><span>RIESLING</span></article></div></section>
<section className="drinkClose"><span>HOUSE OF VEGANO · BEVERAGES</span><h2>DON’T JUST<br/>ORDER A DRINK.<br/><em>BUILD THE MEAL.</em></h2><a href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER FROM THE HOUSE →</a></section></>}{d.testKitchen&&<><section className="testEditorial"><div className="testPortrait"><Image src="/images/thalia-chef-platter.png" alt="Thalia Tatham with House of Vegano creations" fill sizes="55vw"/></div><div className="testWords"><span>THE TEST KITCHEN · 07</span><h2>NO<br/>RULES<br/><em>YET.</em></h2><p>Before a dish becomes part of the House, it gets to be an idea. This is where Thalia experiments.</p></div></section><section className="testExperiment"><img className="officialPhoto" src="https://static.spotapps.co/spots/5e/2c1afb6a71456cae33a86586a70aa7/full" alt="House of Vegano signature roll"/><div><small>EXPERIMENT · TASTE · DECIDE · REPEAT</small><strong>WHAT<br/>HAPPENS<br/><em>NEXT?</em></strong></div></section></>}{d.dessert&&<><section className="dessertEditorial"><div><span>THE LAST COURSE · 04</span><h2>SAVE<br/><em>ROOM.</em></h2><p>The ending should be every bit as memorable as the first bite. House of Vegano treats dessert like its own destination—creamy, layered, bright and worth staying for.</p><div className="dessertTags"><b>CREAMY</b><b>BRIGHT</b><b>DECADENT</b><b>HOUSE FINISH</b></div></div><figure><img className="officialPhoto" src="https://static.spotapps.co/spots/56/031328c8ed48eabc685c378ce80859/full" alt="House of Vegano vegan tiramisu"/></figure></section>
<section className="dessertFeatureGrid"><article className="dessertFeature dessertFeatureTall"><img src="https://static.spotapps.co/spots/81/548e0a2f0f4cbf86a8bbd67079d39c/full" alt="House of Vegano cheesecake desserts"/><div><small>CHEESECAKE</small><strong>GUAVA ROSE</strong><p>Fresh guava, creamy cashew base and a celestial chunk cookie foundation.</p></div></article><article className="dessertFeature"><img src="https://static.spotapps.co/spots/49/cf50f1e2c047ca85d908170f4fa18d/full" alt="House of Vegano vegan tiramisu"/><div><small>TIRAMISU</small><strong>THE CLASSIC FINISH</strong><p>A from-scratch signature built around richness, balance and a proper last bite.</p></div></article><article className="dessertFeature"><img src="https://static.spotapps.co/spots/58/f6b5fa4b88425abcf44260cde9851b/full" alt="House of Vegano tropical cheesecake dessert"/><div><small>CHEESECAKE</small><strong>PASSION FRUIT</strong><p>Tropical fruit and vanilla with a house-made syrup finish.</p></div></article></section>
<section className="dessertStory"><div><span>THE SWEET SIDE OF THE HOUSE</span><h2>NOT AN<br/>AFTERTHOUGHT.<br/><em>THE FINALE.</em></h2><p>The menu also includes a Strawberry Matcha Tiramisu with vanilla layers, matcha-flavored ladyfingers and strawberries macerated in rosé wine.</p><a href="/menu">SEE THE CURRENT DESSERT MENU →</a></div><figure><img className="officialPhoto" src="https://static.spotapps.co/spots/81/548e0a2f0f4cbf86a8bbd67079d39c/full" alt="House of Vegano Guava Rose Cheesecake"/></figure></section>
<section className="dessertPairing"><div><span>ONE MORE THING</span><h2>STAY FOR<br/><em>DESSERT.</em></h2><p>The official drink menu pairs Riesling with all of the desserts, giving the last course its own pairing moment instead of treating it like an add-on.</p><a href="/menu/beverages">EXPLORE THE DRINKS →</a></div><div className="dessertPairingCard"><img src="https://static.spotapps.co/spots/ce/a90a531f1f4aaaac27e6b2db34e2fe/full" alt="House of Vegano beverage"/><div><small>PAIR THE LAST COURSE</small><strong>RIESLING + SWEET FINISH</strong><a href="/menu/beverages">BUILD THE PAIRING →</a></div></div></section>
<section className="dessertClose"><span>HOUSE OF VEGANO · DESSERTS</span><h2>THE LAST BITE<br/>SHOULD STILL<br/><em>SURPRISE YOU.</em></h2><a href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER FROM THE HOUSE →</a></section></>}{d.ramen&&<><section className="ramenEditorial"><figure><img className="officialPhoto" src="https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full" alt="House of Vegano Tom Kha ramen"/></figure><div><span>THE BOWL · 05</span><h2>DEEP.<br/>WARM.<br/><em>HOUSE.</em></h2><p>Ramen at House of Vegano is built for the moment when you want something slower, warmer and completely absorbing.</p><div className="ramenTags"><b>LEMONGRASS</b><b>COCONUT</b><b>CHILI</b><b>COMFORT</b></div></div></section>
<section className="ramenBuild"><div><span>WHAT MAKES THE BOWL</span><h2>LAYERS<br/>OF <em>COMFORT.</em></h2><p>The experience starts with the broth and builds outward—aroma, richness, heat, vegetables and texture working together in one bowl.</p></div><ol><li><b>01</b><strong>THE BROTH</strong><p>Chili, lemongrass and coconut create a base that is bright, creamy and deeply aromatic.</p></li><li><b>02</b><strong>THE BODY</strong><p>Noodles, corn and scallions make the bowl substantial without losing the freshness underneath.</p></li><li><b>03</b><strong>THE FINISH</strong><p>Vegan vork belly and heat bring the richness and contrast that turn it from soup into a full House moment.</p></li></ol></section>
<section className="ramenMoment"><div><span>TOM KHA RAMEN</span><strong>STAY<br/><em>A WHILE.</em></strong><p>Warm enough to slow you down. Bold enough to keep you thinking about it after you leave.</p></div><img className="officialPhoto" src="https://static.spotapps.co/spots/6d/62cd163c7d4dc8b62aadd05bf3926f/full" alt="House of Vegano Tom Kha ramen"/></section>
<section className="ramenPairing"><div className="ramenPairingCopy"><span>MAKE IT A MEAL</span><h2>START<br/>BRIGHT.<br/><em>FINISH WARM.</em></h2><p>Pair the bowl with something crisp or shareable first—dumplings, sushi or a lighter side—then let the ramen own the middle of the table.</p><a href="/menu">EXPLORE THE FULL MENU →</a></div><div className="ramenPairingCards"><article className="ramenPairCard ramenPairCardDumplings"><img src="https://static.spotapps.co/spots/22/58ca1f2ae243adbe7beef55769878a/full" alt="House of Vegano dumplings"/><div><strong>DUMPLINGS</strong><p>Soft, saucy and made for sharing before the bowl arrives.</p><a href="/menu/dumplings">ENTER THE DUMPLINGS →</a></div></article><article className="ramenPairCard ramenPairCardRolls"><img src="https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full" alt="House of Vegano signature rolls"/><div><strong>SIGNATURE ROLLS</strong><p>Color and contrast before the warmth of the ramen.</p><a href="/menu/rolls">EXPLORE THE ROLLS →</a></div></article></div></section>
<section className="ramenClose"><span>HOUSE OF VEGANO · RAMEN</span><h2>NOT JUST A BOWL.<br/><em>A RESET.</em></h2><a href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER FROM THE HOUSE →</a></section></>}{d.rolls&&<><section className="rollsEditorial"><div className="rollsWord">ROLL<br/><em>WITH IT.</em></div><figure><img className="officialPhoto" src="https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full" alt="House of Vegano signature sushi board"/></figure><div className="rollsNote"><span>THE HOUSE · 01</span><p>Not imitation. Not compromise. A different idea of what sushi can be—built around mushrooms, vegetables, fruit, sauces, heat and texture.</p><div className="rollsTags"><b>COLOR</b><b>TEXTURE</b><b>HEAT</b><b>UMAMI</b></div></div></section>
<section className="rollsStrip"><img className="officialPhoto" src="https://static.spotapps.co/spots/e3/a4cf0cbd0545be875e5f25a082fa24/full" alt="House of Vegano Still I Rise roll"/><div>COLOR · TEXTURE · PRECISION · HOUSE</div></section>
<section className="rollsPhilosophy"><div><span>THE HOUSE METHOD</span><h2>BUILD THE<br/><em>BITE.</em></h2><p>Every signature roll is designed as a complete experience. Richness needs acid. Softness needs crunch. Heat needs something cool beside it. The roll works when every element has a job.</p></div><div className="rollsSteps"><article><b>01</b><strong>FOUNDATION</strong><p>Rice, nori, vegetables and the structure that keeps the bite together.</p></article><article><b>02</b><strong>TEXTURE</strong><p>King oyster, lion’s mane, avocado, crisp crumbs and layered contrast.</p></article><article><b>03</b><strong>FINISH</strong><p>House sauces, heat, torched elements, caviar and color that make the roll unmistakably Vegano.</p></article></div></section>
<section className="rollsSignatures"><div className="rollsSignaturesIntro"><span>SIGNATURES TO KNOW</span><h2>START<br/>HERE.</h2><p>Four rolls that tell the House story from different directions.</p></div><div className="rollsCards"><article><img src="https://static.spotapps.co/spots/5e/2c1afb6a71456cae33a86586a70aa7/full" alt="Adriana Vegano Sparkle II roll"/><div><span>01</span><h3>ADRIANA “VEGANO” SPARKLE II</h3><p>Vegan sckallop, cucumber and avocado topped with house toona tartare and 24-karat gold sparkle.</p><strong>SHOWSTOPPER</strong></div></article><article><img src="https://static.spotapps.co/spots/19/df68b6b6464223ab75475f858e73cf/full" alt="Spicy Tuna roll"/><div><span>02</span><h3>SPICY TOONA</h3><p>Marinated tomato toona, avocado and cucumber with spicy mayo.</p><strong>BRIGHT + SPICY</strong></div></article><article><img src="https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full" alt="Rainbow Roll"/><div><span>03</span><h3>RAINBOW ROLL</h3><p>Krab, cucumber and avocado topped with toona, mango, unagi and avocado.</p><strong>COLOR + CONTRAST</strong></div></article><article><img src="https://static.spotapps.co/spots/1e/625e4f72784322b93a681619b32b35/full" alt="The Burg roll"/><div><span>04</span><h3>THE BURG</h3><p>Eggplant, cucumber, tempura crumbs, torched avocado, lion’s mane, king oyster and vegan lobstah.</p><strong>RICH + TORCHED</strong></div></article></div></section>
<section className="rollsClose"><span>HOUSE OF VEGANO · ST. PETERSBURG</span><h2>THE ROLL ISN’T<br/>THE ALTERNATIVE.<br/><em>IT’S THE REASON.</em></h2><a href="/menu">SEE THE FULL MENU →</a></section></>}{d.obsession&&<><section className="dumplingEditorial"><div className="dumplingNumber">01</div><div><p>THE HOUSE OBSESSION</p><h2>SOFT.<br/>TENDER.<br/><em>RIDICULOUS.</em></h2></div><figure><img className="officialPhoto" src="https://static.spotapps.co/spots/22/58ca1f2ae243adbe7beef55769878a/full" alt="House of Vegano dumplings"/></figure></section><section className="dumplingQuote"><div>★★★★★</div><blockquote>“Just had the best dumplings ever. Who knew they were vegan?”</blockquote><span>GREGGORY BUTLER · GOOGLE REVIEW</span></section></>}
{slug==="test-kitchen"&&<><section className="depthSplit testDepth"><div><span>THALIA'S LAB · BEFORE THE MENU</span><h2>IDEA.<br/>TEXTURE.<br/><em>THEN THE BITE.</em></h2><p>The Test Kitchen is the creative edge of the House: a place to push mushrooms, vegetables, sauces, texture and presentation before an idea earns a permanent place.</p><div className="depthTags"><b>EXPERIMENT</b><b>TASTE</b><b>REFINE</b><b>DECIDE</b></div></div><figure><img src="https://static.spotapps.co/spots/5e/2c1afb6a71456cae33a86586a70aa7/full" alt="House of Vegano creative signature roll"/></figure></section><section className="roomImageStrip"><figure><img src="https://static.spotapps.co/spots/b9/4ffdf1e852484a90061289ba98cfc7/full" alt="House of Vegano vegan nigiri sampler"/><figcaption>NIGIRI · DETAIL + PRECISION</figcaption></figure><figure><img src="https://static.spotapps.co/spots/8e/75c92c2ce74cc1b27b38c193a44dd0/full" alt="House of Vegano Rainbow Roll"/><figcaption>ROLLS · COLOR + CONTRAST</figcaption></figure></section><section className="depthCards"><article><small>01 · START</small><strong>THE IDEA</strong><p>A flavor, ingredient or visual direction starts the conversation.</p></article><article><small>02 · BUILD</small><strong>THE CONTRAST</strong><p>Soft against crisp. Sweet against heat. Richness against acid.</p></article><article><small>03 · EARN IT</small><strong>THE HOUSE TEST</strong><p>If it feels unmistakably House of Vegano, it can move forward.</p></article></section></>}

{slug==="poke-bowl"&&<><section className="depthSplit pokeDepth"><figure><img src="https://static.spotapps.co/spots/c9/8f265be6d64e4fa455a6e9421a0dd4/full" alt="House of Vegano colorful plant-based spread"/></figure><div><span>THE BOWL · BUILT IN LAYERS</span><h2>COLOR.<br/>TEXTURE.<br/><em>CONTRAST.</em></h2><p>Thalia has described the poke idea as a big, deconstructed sushi roll. That is the right way to read this room: the same House ingredients, sauces, color and contrast—opened up into a bowl instead of wrapped into a roll.</p><div className="depthTags"><b>FRESH</b><b>LAYERED</b><b>PLANT-BASED</b><b>HOUSE FLAVOR</b></div><a href="/menu">SEE THE CURRENT MENU →</a></div></section><section className="roomImageStrip"><figure><img src="https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full" alt="House of Vegano sushi ingredients and toppings"/><figcaption>THE SAME HOUSE LANGUAGE · OPENED UP</figcaption></figure><figure><img src="https://static.wixstatic.com/media/eb333a_ca87d16efa5b46238a3a9b5458546b6d~mv2.jpg/v1/fill/w_980,h_490,al_c,q_85,enc_auto/eb333a_ca87d16efa5b46238a3a9b5458546b6d~mv2.jpg" alt="House of Vegano plant-based sushi and toppings"/><figcaption>RICE · SAUCE · TEXTURE · COLOR</figcaption></figure></section><section className="depthCards"><article><small>01 · BASE</small><strong>BUILD THE FOUNDATION</strong><p>Start clean and let every layer have a reason to be there.</p></article><article><small>02 · TEXTURE</small><strong>MAKE IT MOVE</strong><p>Creamy, crisp, tender and bright should all show up in the same bowl.</p></article><article><small>03 · FINISH</small><strong>SAUCE WITH PURPOSE</strong><p>The final layer should connect the bowl, not bury it.</p></article></section></>}

{slug==="special-event"&&<><section className="depthSplit eventDepth"><figure><img src="https://static.spotapps.co/spots/1e/113c83da734d3799ceeee67744e582/wide_medium" alt="House of Vegano spacious seating area with large windows"/></figure><div><span>PRIVATE PARTIES · 1990 CENTRAL AVE</span><h2>YOUR PEOPLE.<br/>YOUR NIGHT.<br/><em>THE HOUSE.</em></h2><p>The room already brings the color, art and personality. House of Vegano's group-reservation experience is built for birthdays, showers, office functions, anniversaries, graduations and other gatherings.</p><div className="depthTags"><b>6–25 GUESTS</b><b>BIRTHDAYS</b><b>OFFICE FUNCTIONS</b><b>CELEBRATIONS</b></div><a href="https://tmt.spotapps.co/private-parties?callback_url=http%3A%2F%2Fhouseofvegano.com%2F&spot_id=109242" target="_blank" rel="noreferrer">BOOK YOUR PARTY →</a></div></section><section className="eventGallery"><img src="https://static.spotapps.co/spots/27/ac6ef4152949d0b8ecdfbaa1c57ba3/wide_medium" alt="House of Vegano interior with painted mural"/><img src="https://static.spotapps.co/spots/3f/d404bdb5bb4092aba3a73542386cbb/wide_medium" alt="House of Vegano seating near windows"/><img src="https://static.spotapps.co/spots/49/7633410b0144fda313508e6311d55a/wide_medium" alt="House of Vegano dining area with mural"/></section></>}

{slug==="lunch-special"&&<><section className="depthSplit lunchDepth"><div><span>CURRENT LUNCH SPECIAL</span><h2>TWO ROLLS.<br/>ONE DRINK.<br/><em>$25.</em></h2><p>House of Vegano's current lunch special is built for a fast, satisfying middle of the day: choose two classic rolls and a drink. Dine-in only, currently offered from 11 AM to 2 PM on listed special days.</p><div className="depthTags"><b>2 CLASSIC ROLLS</b><b>1 DRINK</b><b>$25</b><b>DINE-IN</b></div><a href="/specials">CHECK TODAY’S SPECIAL →</a></div><figure><img src="https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full" alt="House of Vegano sushi spread for lunch"/></figure></section><section className="roomImageStrip lunchImageStrip"><figure><img src="https://static.spotapps.co/spots/43/b7fab7b2ec420e90c7db99b2b78da5/full" alt="House of Vegano roll selection"/><figcaption>PICK TWO · MIX + MATCH</figcaption></figure><figure><img src="https://static.spotapps.co/spots/e3/a4cf0cbd0545be875e5f25a082fa24/full" alt="House of Vegano Still I Rise roll"/><figcaption>MAKE LUNCH THE GOOD PART OF THE DAY</figcaption></figure></section><section className="depthCards"><article><small>01 · PICK</small><strong>CHOOSE TWO ROLLS</strong><p>Mix and match classic rolls based on what you want that day.</p></article><article><small>02 · POUR</small><strong>ADD THE DRINK</strong><p>One simple lunch format with enough variety to keep it interesting.</p></article><article><small>03 · COME IN</small><strong>MAKE LUNCH COUNT</strong><p>Dine in, slow down for a minute, then get back to the day.</p></article></section></>}

{d.theme&&<section className={"categorySignature "+d.theme}><span>{d.eyebrow}</span><strong>{d.theme==="dessert"?"SAVE ROOM.":d.theme==="ramen"?"STAY A WHILE.":d.theme==="drinks"?"POUR. SIP. STAY.":d.theme==="test"?"NO RULES YET.":d.theme==="event"?"GATHER HERE.":d.theme==="lunch"?"MAKE LUNCH COUNT.":d.theme==="poke"?"BUILD THE BOWL.":"SMALL PLATES. BIG ENERGY."}</strong></section>}<section className="categoryDiptych"><figure>{d.second.startsWith("http")?<img className="categoryRemotePhoto" src={d.second} alt={d.title+" House of Vegano"}/>:<Image src={"/images/"+d.second} alt={d.title+" House of Vegano"} fill sizes="60vw"/>}</figure><div><small>THALIA’S HOUSE</small><h2>COME<br/>TASTE<br/><em>WHY.</em></h2><p>Plant-based. Chef-driven. Made to be remembered.</p><a href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER FROM THE HOUSE →</a></div></section>
<footer className="categoryFooter"><a href="/">HOUSE OF VEGANO</a><span>1990 CENTRAL AVE · ST. PETERSBURG</span><a href="/menu">EXPLORE THE FULL MENU →</a></footer>
<a className="mobileOrder" href="https://tmt.spotapps.co/ordering-menu?spot_id=109242&accordion=true&images=yes" target="_blank" rel="noreferrer">ORDER NOW ↗</a>
</main>}